dist: xenial
language: python
stages:
  - "Static code analysis"
  - test
  - deploy
notifications:
  email: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
script:
  # run tests, and get coverage:
  - python -m pytest --cov=src/
  # test that the notebooks all run smoothly
#   - find docs -name '*.ipynb' -maxdepth 2 | xargs jupyter nbconvert --to notebook --execute
  # submit coverage report to coveralls
  - python -m coveralls
  # - ls -la
install:
  - pip install --upgrade -qq pip flit
  - flit install --symlink --extras=test
  - pip install --upgrade -qq 'attrs>=19.3.0'
jobs:
  include:
    - stage: "Static code analysis"
      name: "black formatting test"
      install:
        - pip install -qq black
      script:
        - black --check src/
      python: "3.7"
    - stage: "Static code analysis"
      name: "flake8 check"
      install:
        - pip install -qq flake8
      script:
        - flake8 src/
      python: "3.7"
    - stage: "Static code analysis"
      name: "mypy check"
      script:
        - mypy --ignore-missing-imports src/
      python: "3.7"
      install:
        - pip install -qq mypy
    - stage: deploy
      name: "Deploy to pypi"
      if: tag IS present
      install:
        - pip install flit
      script:
        - flit build
        - env FLIT_USERNAME=$PYPI_USER FLIT_PASSWORD=$PYPI_PASSWORD flit publish
      python: "3.7"
